### ISSUE TITLE
Recommended alerts have links to aka.ms which is not reachable

### ISSUE THREAD

**Issue by jmelching** [Azure/prometheus-collector#806]
The recommended alerts configured below give links to an internal microsoft site (ie. https://aka.ms/aks-alerts/pod-level-recommended-alerts).  Please update to provide the correct links.

https://raw.githubusercontent.com/Azure/prometheus-collector/main/GeneratedMonitoringArtifacts/Default/recommendedMetricAlerts.json

**Comment by vishiy** [comment]
This should be fixed now. please confirm. @jmelching

**Comment by jmelching** [comment]
@vishiy i'm still getting {"code":403,"message":"User \"jeff.melching@freightscience.com\" is not authorized to access this URL."} when attempting to hit any of the urls like this : https://aka.ms/aks-alerts/cluster-level-recommended-alerts

**Comment by vishiy** [comment]
Hi @jmelching - i have updated all the pseduo links. Can you please check & confirm. Apologies for the confusion.

**Comment by jmelching** [comment]
Working now.
